### PR TITLE
fix: Trigger github actions for PRs

### PR DESCRIPTION
**Pull request by jirihnidek**
* Github actions were triggered only for push
* Tests and bulding of packages are triggered for PRs too

### CODE REVIEW

**Review by ahitacat — APPROVED** [review]
LGTM

**Comment by jirihnidek** [comment]
@subpop it seems that this PR requires your review, because it's probably only you, who can approve it and merge it.

Can you give us more permissions for this repository?

**Comment by subpop** [comment]
I added @ahitacat as an Admin. @jirihnidek , you were already Maintainer, so I upgraded you to Admin.

**Review by subpop — APPROVED** [review]
LGTM

**Pull request merged**
